name: nf-pipelines
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bismark=0.23.0
  - fastqc=0.11.9
  - trim-galore=0.6.7
  - multiqc=1.11
  - fastq-screen=0.13.0
  - picard=2.25.7
  - pip
  - pip:
    - /users/thomas.ellis/pyBsHap/